/* eslint-disable */
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
    "API_URL": "https://rest-api-node-js-d0lf.onrender.com/api",
    "QUIZE_URL": "https://opentdb.com/api.php",
    "ENV": "development"
  };
  